version: '3.9'

services:
    app:
        restart: always
        container_name: exchange_app
        build:
            context: ./docker/php
            args:
                UID: $UID
                GUID: $GUID
        working_dir: /var/www/html/app
        depends_on:
            - mysql
            - redis-cache
        ports:
            - '8881:8000'
        volumes:
            - ./shared/app:/var/www/html/app

    mysql:
        restart: always
        image: mysql:5.7
        volumes:
            - ./shared/mysql/db:/var/lib/mysql:z
            - ./shared/backup/mysql:/backup:z
        ports:
            - $DB_PORT:3306
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD

    scheduler:
        restart: always
        build:
            context: ./docker/php-cli
            args:
                UID: $UID
                GUID: $GUID
        entrypoint: [ "php", "bin/console", "schedule:run" ]
        volumes:
            - ./shared/app:/var/www/html/app
        working_dir: /var/www/html/app
        depends_on:
            - app

    redis-cache:
        restart: always
        image: redis:6.2.6-alpine
        volumes:
            - redis-cache:/data

    redis-worker:
        restart: always
        image: redis:6.2-alpine
        volumes:
            - redis-worker:/data

    worker-update-rate:
        restart: always
        user: $UID:$GUID
        build:
            context: ./docker/php-cli
            args:
                UID: $UID
                GUID: $GUID
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--limit=100", "--time-limit=3600", "-vv" ]
        volumes:
            - ./shared/app:/var/www/html/app
        working_dir: /var/www/html/app
        depends_on:
            - redis-worker
            - app

volumes:
    redis-cache:
    redis-worker: